name: Run Tests

on:
    pull_request:
      branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Install dependencies
      run: yarn --frozen-lockfile
    
    - name: Run Lint
      run: yarn lint

    - name: Run Type Check
      run: yarn type-check

    - name: Build
      run: yarn build  

    - name: Run Tests
      run: yarn test 
