name: Run Tests

on:
    pull_request:
      branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node modules
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
            
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build  

    - name: Run Tests
      run: yarn test 
